import type { Metadata } from "next";
import "./globals.css";
import { storyblokInit, apiPlugin } from "@storyblok/react/rsc"; 
import Teaser from "./components/Teaser";
import Grid from "./components/Grid";
import Feature from "./components/Feature";
import Page from "./components/Page";
import StoryblokProvider from "./components/StoryblokProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const components = {
  teaser: Teaser,
  grid: Grid,
  page: Page,
  feature: Feature,
}

storyblokInit({
  accessToken: "ZSCyML5yxIGKaWfielJWBQtt",
  use: [apiPlugin],
  components,
  apiOptions: {
    region: ""
  }
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </StoryblokProvider>
  );
}
